homeassistant:
  name: Remote Dev
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 102
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages

http:
  base_url: !secret base_url

lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-card-tools/card-tools.js
      type: module
    - url: /local/community/lovelace-layout-card/layout-card.js
      type: module
    - url: /local/community/lovelace-state-switch/state-switch.js
      type: module
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/decluttering-card/decluttering-card.js
      type: module


config:

discovery:
  ignore:
    - google_cast
    - apple_tv
    - ikea_tradfri
    - tellstick
    - esphome

history:

logbook:

system_health:

hacs:
  token: !secret my_github_access_token