title: Home Control Panel
resources:
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/lovelace-card-modder/card-modder.js
    type: js
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module 
  - url: /community_plugin/lovelace-state-switch/state-switch.js
    type: js

###################################################################################################
## Custom Compact Header - Main config is in here
###################################################################################################
cch:
  exceptions:
    - conditions:
        user: remote
      config:
        disable: false
        options: clock
        clock_format: 24
        menu: show
        notification: hide

views:
  - !include lovelace/remote_navigation.yaml