title: Home Control Panel
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/card-modder.js
    type: js
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /customcards/state-switch.js
    type: js
  - url: /customcards/layout-card.js
    type: js

views:
  - !include lovelace/remote_navigation.yaml
  - !include lovelace/settings.yaml
