title: Home Control Panel
resources:
  - url: /customcard/tracker-card.js
    type: js
  - url: /customcard/card-tools.js
    type: js
  - url: /customcard/card-modder.js
    type: js
  - url: /customcard/compact-custom-header.js
    type: module
  - url: /customcard/state-switch.js
    type: js
  - url: /customcard/layout-card.js
    type: js

views:
  - !include lovelace/remote.yaml
  - !include lovelace/settings.yaml
