title: Home Control Panel
resources:
  - url: /local/community/lovelace-card-tools/card-tools.js
    type: module
  - url: /local/community/lovelace-layout-card/layout-card.js
    type: module
  - url: /local/community/lovelace-state-switch/state-switch.js
    type: module
  - url: /local/community/button-card/button-card.js
    type: module

views:
  - !include lovelace/remote_navigation.yaml