---
############################################################################
## Control Nvidia Shield TV (https://megamorphf.github.io/homeassistant/hyperion/ssh/hassio/2018/01/22/controlling-anything-via-ssh.html)
## Spin up sorccu/adb docker container on another VM (other ip adress)
############################################################################
## Input Booleans (Activates the node-red flows)
############################################################################
input_boolean:
  twitch_trigger:
    name: trigger twitch
    initial: off
    icon: mdi:twitch
  youtube_trigger:
    name: trigger youtube
    initial: off
    icon: mdi:youtube
  kodi_trigger:
    name: trigger kodi
    initial: off
    icon: mdi:kodi
  netflix_trigger:
    name: trigger netflix
    initial: off
    icon: mdi:alpha-c-circle-outline
  cmore_trigger:
    name: trigger cmore
    initial: off
    icon: mdi:youtube
  svtplay_trigger:
    name: trigger svtplay
    initial: off
    icon: mdi:youtube
############################################################################
# Sensor used only to make the mute button change color when active
############################################################################
sensor:
  - platform: template
    sensors:
      shield_app:
        friendly_name: "Shield App"
        value_template: "{{ state_attr('media_player.shield', 'app_name') }}"
############################################################################